### ISSUE TITLE
HTTPS insecure content

### ISSUE THREAD

**Issue by exussum12** [sweetcaptcha/sweetCaptcha-sdk-php#1]
I am currently getting the message 

```
displayed insecure content from http://www.sweetcaptcha.com/api/v2/pixels/{APP ID}?1384795242099.
```

All of the images etc seem to be translated to https but not that one. Changing to https:// produces a insecure certificate error

**Comment by sagish** [comment]
Thanks for the report. It should now be protocol agnostic, kindly confirm.

**Comment by exussum12** [comment]
That works great now !
Thanks
