### ISSUE TITLE
Rightmost image doesnt drag

### ISSUE THREAD

**Issue by exussum12** [sweetcaptcha/sweetCaptcha-sdk-php#2]
The answer furthest to the right does not drag like the others, When one from the left has been dragged, I am able to drag the right one

It is always the answer furthest to the right which this happens to.

Span.holder seems to be causing the issue

```
div.sweetcaptcha span.holder
width: 160px;
```

Reducing that to 90px seems to fix the issue

**Comment by exussum12** [comment]
This is when sweetcapcha is running at less than the max-width, adding a 320px bounding div will show the issue

**Comment by sagish** [comment]
SweetCaptcha is designed to work at a minimal width of 300px (to fit all of it's optional answers). As per your request, the `span.holder` will now take the minimal width necessary so we'd have a more robust and acceptable CSS layout and overrides.

**Comment by exussum12** [comment]
Thanks ! Works much better
