### ISSUE TITLE
Safari 5.1.7 doesnt work

### ISSUE THREAD

**Issue by exussum12** [sweetcaptcha/sweetCaptcha-sdk-php#3]
Hi,

Safari 5.1.7 (latest windows version) doesnt work with sweet captcha., The image icons drag but do not drop on to solve. 

Thanks

**Comment by exussum12** [comment]
May be something to do with this ? http://stackoverflow.com/questions/8782213/ondrop-event-never-fired-for-safari

**Comment by sagish** [comment]
accepted, we'll check it out

**Comment by exussum12** [comment]
Ive seen IE 8 Windows Vista (provided by modern.ie) has a "click" based method rather than a "drag" based similar to the mobile version.

Is that the best option for this safari version  ?

**Comment by sagish** [comment]
Safari should be able to support the drag event, unlike ie 8, and is a very un commonly used under Windows anyhow. Since our scope is currently limited (free service, yay!), if Safari 5.1 is important to you I may suggest you give it a shot yourself, we'll be happy to accept your contribution. Otherwise, we might degrade it to the click behavior.

**Comment by exussum12** [comment]
having the function to `ondragend` of the  elements works, The prevent default of the drop event _seems_ to stop it ever running the dragend event in other compatible browsers. 

So listening to drop on the target and dragend on the li's runs in the browsers ive tested. Safari still shows the Circle with a cross in this solution but thats another issue really

**Comment by exussum12** [comment]
Checked again today, Safari now as the "Click" rather than "Drag" option. This should maybe be closed ?

**Comment by sagish** [comment]
Yup

**Comment by BaljitKarwal** [comment]
what this means: Checked again today, Safari now as the "Click" rather than "Drag" option?

**Comment by BaljitKarwal** [comment]
I am trying to find why drop event not working in safari. please advice.
Thanks
Baljit

**Comment by exussum12** [comment]
@karwalbubble it means that in Safari for Windows, to solve you now have to click the correct answer rather than drag the correct answer. 
I think safari for mac will be ok, Its just a windows issue
