### ISSUE TITLE
Chrome Drag Event

### ISSUE THREAD

**Issue by exussum12** [sweetcaptcha/sweetCaptcha-sdk-php#4]
The Drag event for chrome does not seem to fire, The drop event works and solves the puzzle but the dragging action shows a circle with a line though like it shouldnt be dragged,.

Firefox shows a hand dragging and is the expected behaviour

**Comment by sagish** [comment]
You didn't mention OS and browser version. Anyhow, this is Windows default behavior for HTML5 drag-n-drop elements, reproducible on windows 7 and firefox as well. Sadly we did not find a way to overcome this (the price of discarding jQuery UI for a native, independent functionality), so we're open to suggestions of this. On Mac it acts nicely.

**Comment by exussum12** [comment]
Ah it was Chrome 30. something on Windows. Chromium on Linux works ok.

**Comment by sagish** [comment]
Yes, it true to all Windows clients; you may suggest on this, otherwise it's a non-issue

**Comment by exussum12** [comment]
What about just making the whole thing droppable ? But ignore the event ?

```
ondragover="return false;" ondrop="return false;"
```

to the main div (id sweetcaptcha_number)

That way it "looks" like you are supposed to drag it 

On linux the hand still shows, and when its actually droppable a hand with an arrow appears. Cant test on Mac

**Comment by exussum12** [comment]
Did that work for you ?

**Comment by sagish** [comment]
Works quite well, we'll validate it on all browsers and deploy it soon. Thanks for the contribution!

**Comment by exussum12** [comment]
Seems to be live now, Thanks !
